# Generated by Django 2.1.2 on 2018-11-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(),
        ),
    ]
