# Generated by Django 2.1.2 on 2018-11-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181114_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hash',
        ),
    ]
