# Generated by Django 2.1.2 on 2018-10-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('project_info', models.TextField()),
                ('request_category', models.CharField(blank=None, choices=[('1', 'branding'), ('2', 'editor_design'), ('3', 'webdesign'), ('4', 'packaging'), ('5', 'etc')], max_length=3)),
                ('customer_request_date', models.CharField(blank=True, max_length=30)),
                ('customer_delivery_date', models.CharField(blank=True, max_length=300)),
                ('customer_price', models.PositiveIntegerField(blank=True)),
                ('customer_memo', models.TextField(blank=True)),
            ],
        ),
    ]
