# Generated by Django 2.1.2 on 2018-10-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='customer_delivery_date',
            field=models.CharField(blank=True, max_length=300, verbose_name='마감날짜'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='customer_memo',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='customer_name',
            field=models.CharField(max_length=30, verbose_name='고객명'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='customer_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='예산'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='customer_request_date',
            field=models.CharField(blank=True, max_length=30, verbose_name='시작날짜'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='project_info',
            field=models.TextField(verbose_name='프로젝트 정보'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='request_category',
            field=models.CharField(blank=None, choices=[('1', '브랜딩'), ('2', '편집디자인'), ('3', '웹디자인'), ('4', '패키징'), ('5', '기타')], max_length=3, verbose_name='요청카테고리'),
        ),
    ]
