# Generated by Django 2.1.2 on 2018-10-30 16:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0002_auto_20181028_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='request_category',
            field=multiselectfield.db.fields.MultiSelectField(blank=None, choices=[('1', '브랜딩'), ('2', '편집디자인'), ('3', '웹디자인'), ('4', '패키징'), ('5', '기타')], max_length=9, verbose_name='요청카테고리'),
        ),
    ]
