# Generated by Django 2.1.2 on 2018-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0003_auto_20181031_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
